name: python application

on:
  push: 
    branches: [ master]
  pull_request: 
    branches: [ master ] 


jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/inviz-ai-mohan/privatemodule
      GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    strategy:
      matrix:
        python-version: [3.7.9]

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
    
    - name: setup python ${{ matrix.python.version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python.version }}

    - name: install dependies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: install kubectl
      uses: eks/setup-kubectl@v2.0
      with:
        version: '1.24.0'
      id: install

